name: Build & Deploy

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            cd paperdaz-app
            git pull origin master
            cd paperdaz-app/Paperdaz-2.0
            yarn install
            yarn generate
            rm -r /var/www/test/*
            mv -t /var/www/test/ ./dist/*
            echo 'Deployment successful to digital ocean'
