name: Build & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull Paperdaz App
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
            nvm use 16.19.0
            echo 'Used Node JS v16.19.0'
            cd paperdaz-app/Paperdaz-2.0
            git pull origin main
            echo 'Pull successful to digital ocean'
            node -v
            npm install yarn -g
            yarn install
            echo 'Installed successfully'
            yarn generate
            echo 'Built successfully'
            rm -rf /var/www/test/*
            mv -t /var/www/test/ ./dist/*
            echo 'Deployment successful to digital ocean'
            
